-- Enable Row Level Security (RLS) recommended for Supabase
CREATE TABLE shift_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_date DATE NOT NULL,
    emp_id TEXT NOT NULL,
    emp_name TEXT NOT NULL,
    team TEXT NOT NULL,
    shift_type TEXT NOT NULL CHECK (shift_type IN ('Day', 'Swing', 'Night', 'OFF')),
    work_type TEXT NOT NULL DEFAULT 'Regular' CHECK (work_type IN ('Regular', 'Overtime', 'Leave')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(work_date, emp_id)
);

-- Index for fast lookups by Date and Team
CREATE INDEX idx_schedules_date_team ON shift_schedules (work_date, team);

-- RLS Policy: Allow Read for everyone (authenticated)
ALTER TABLE shift_schedules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read" ON shift_schedules
    FOR SELECT USING (true);

-- Time-Lock Policy (Database Level Protection)
-- "Target_Date >= Today": Allow Update/Insert
-- "Target_Date < Today": Deny (Prevent history tampering)
CREATE POLICY "Allow update for future dates only" ON shift_schedules
    FOR UPDATE USING (
        work_date >= CURRENT_DATE
    ) WITH CHECK (
        work_date >= CURRENT_DATE
    );

CREATE POLICY "Allow insert for future dates only" ON shift_schedules
    FOR INSERT WITH CHECK (
        work_date >= CURRENT_DATE
    );
